/**********
 * hdrs.h *
 **********/
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <io.h>
#include <wslxa.h>
#include "standard.h"
#include "defines.h"
#include "mcxc.h"
#include "io.h"
#include "mcxdef.h"

#include "timers.h"
#include "keypad.h"
#include "util.h"
#include "dev.h"
#include "main.h"
#include "rsrc.h"
#include "sci.h"
#include "mdb.h"
#include "coin.h"
#include "bill.h"
#include "card.h"
#include "dex.h"
#include "vend.h"
#include "display.h"
#include "mcxdbug.h"
#include "mis.h"
#include "menu.h"
#include "globals.h"
#include "bram.h"
#include "eeprom.h"