/***********************
* timers.h --          *
*   Timer definitions. *
************************/


#define MS   4                /*  milliseconds per tick */
#define TM_4ms      4/MS
#define TM_8ms      8/MS
#define TM_12ms    12/MS
#define TM_16ms    16/MS
#define TM_20ms    20/MS
#define TM_30ms    30/MS
#define TM_40ms    40/MS
#define TM_50ms    50/MS
#define TM_80ms    80/MS
#define TM_100ms  100/MS
#define TM_120ms  120/MS
#define TM_200ms  200/MS
#define TM_250ms  250/MS
#define TM_300ms  300/MS
#define TM_400ms  400/MS
#define TM_500ms  500/MS
#define TM_600ms  600/MS
#define TM_800ms  800/MS
#define TM_1sec  1000/MS
#define TM_2sec  2000/MS
#define TM_3sec  3000/MS
#define TM_4sec  4000/MS
#define TM_5sec  5000/MS
#define TM_10sec 10000/MS
#define TM_20sec 20000/MS
#define TM_30sec 30000/MS
#define TM_1min  60000/MS
#define SERVICE_TIMEOUT 3*TM_1min

